# Generated by Django 3.1.1 on 2020-09-07 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='Execution_tag',
            new_name='execution_tag',
        ),
        migrations.RemoveField(
            model_name='execution',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='execution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 9, 41, 24, 429140)),
        ),
    ]
